require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - '**/*.gemspec'
    - 'spec/**/*'

Metrics/ClassLength:
  Exclude:
    - 'spec/support/fake_*.rb'

Metrics/MethodLength:
  Max: 40
  Exclude:
    - 'spec/support/fake_*.rb'

Metrics/AbcSize:
  Max: 40

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 20

Naming/VariableNumber:
  EnforcedStyle: snake_case

RSpec/FilePath:
  Exclude:
    - spec/lib/simpal/paypal_object_spec.rb
