name: Ruby

on:
  workflow_dispatch:
  push:

jobs:
  rubocop:
    name: RuboCop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout Source Code
      - uses: ruby/setup-ruby@v1
        name: Setup Ruby
        with:
          ruby-version: 3.0
          bundler-cache: true
      - name: RuboCop
        run: bundle exec rubocop --parallel --fail-level warning --format progress --format html --out rubocop-report.html
      - uses: actions/upload-artifact@v1
        name: Upload Report
        if: always()
        with:
          name: RuboCop Report
          path: rubocop-report.html

  rspec:
    name: RSpec
    strategy:
      fail-fast: false
      matrix:
        platform:
          - macos-latest
          - ubuntu-latest
        ruby-version:
          - '2.6'
          - '2.7'
          - '3.0'
          - '3.1'
          - head
          - jruby
          - truffleruby
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
        name: Checkout Source Code
      - uses: ruby/setup-ruby@v1
        name: Setup Ruby
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: RSpec
        run: bundle exec rspec --format progress --format html --out rspec-report.html
      - uses: actions/upload-artifact@v1
        name: Upload Report
        if: always()
        with:
          name: RSpec Report
          path: rspec-report.html
